name: TranslationKeyboard
options:
  bundleIdPrefix: com.translk
  xcodeVersion: "15.4"
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGN_ENTITLEMENTS: ""
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  TranslationKeyboard:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - "*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.translk.app
        INFOPLIST_FILE: App/Info.plist
        ENABLE_BITCODE: "NO"
        CODE_SIGN_ENTITLEMENTS: App/TranslationKeyboard.entitlements
    dependencies:
      - target: TranslationKeyboardExtension

  TranslationKeyboardExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: Keyboard
        excludes:
          - "*.entitlements"
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.translk.app.keyboard
        INFOPLIST_FILE: Keyboard/Info.plist
        ENABLE_BITCODE: "NO"
        CODE_SIGN_ENTITLEMENTS: Keyboard/KeyboardExtension.entitlements
