import Foundation

struct Language: Hashable, Codable {
    let code: String
    let name: String
}

enum Languages {
    static let autoDetect = Language(code: "auto", name: "Auto-detect")

    static let all: [Language] = [
        // Kurdish dialects — top of list for easy access
        Language(code: "ku-bad", name: "Kurdish (Badini)"),
        Language(code: "ku-ckb", name: "Kurdish (Sorani)"),
        Language(code: "ku",     name: "Kurdish (Kurmanji)"),
        Language(code: "ar",    name: "Arabic"),
        Language(code: "bn",    name: "Bengali"),
        Language(code: "bg",    name: "Bulgarian"),
        Language(code: "ca",    name: "Catalan"),
        Language(code: "zh",    name: "Chinese (Simplified)"),
        Language(code: "zh-TW", name: "Chinese (Traditional)"),
        Language(code: "hr",    name: "Croatian"),
        Language(code: "cs",    name: "Czech"),
        Language(code: "da",    name: "Danish"),
        Language(code: "nl",    name: "Dutch"),
        Language(code: "en",    name: "English"),
        Language(code: "et",    name: "Estonian"),
        Language(code: "fi",    name: "Finnish"),
        Language(code: "fr",    name: "French"),
        Language(code: "de",    name: "German"),
        Language(code: "el",    name: "Greek"),
        Language(code: "gu",    name: "Gujarati"),
        Language(code: "he",    name: "Hebrew"),
        Language(code: "hi",    name: "Hindi"),
        Language(code: "hu",    name: "Hungarian"),
        Language(code: "is",    name: "Icelandic"),
        Language(code: "id",    name: "Indonesian"),
        Language(code: "ga",    name: "Irish"),
        Language(code: "it",    name: "Italian"),
        Language(code: "ja",    name: "Japanese"),
        Language(code: "kn",    name: "Kannada"),
        Language(code: "km",    name: "Khmer"),
        Language(code: "ko",    name: "Korean"),
        Language(code: "ku",    name: "Kurdish"),
        Language(code: "lv",    name: "Latvian"),
        Language(code: "lt",    name: "Lithuanian"),
        Language(code: "ms",    name: "Malay"),
        Language(code: "ml",    name: "Malayalam"),
        Language(code: "mr",    name: "Marathi"),
        Language(code: "no",    name: "Norwegian"),
        Language(code: "fa",    name: "Persian"),
        Language(code: "pl",    name: "Polish"),
        Language(code: "pt",    name: "Portuguese"),
        Language(code: "pa",    name: "Punjabi"),
        Language(code: "ro",    name: "Romanian"),
        Language(code: "ru",    name: "Russian"),
        Language(code: "sr",    name: "Serbian"),
        Language(code: "si",    name: "Sinhala"),
        Language(code: "sk",    name: "Slovak"),
        Language(code: "sl",    name: "Slovenian"),
        Language(code: "es",    name: "Spanish"),
        Language(code: "sw",    name: "Swahili"),
        Language(code: "sv",    name: "Swedish"),
        Language(code: "ta",    name: "Tamil"),
        Language(code: "te",    name: "Telugu"),
        Language(code: "th",    name: "Thai"),
        Language(code: "tr",    name: "Turkish"),
        Language(code: "uk",    name: "Ukrainian"),
        Language(code: "ur",    name: "Urdu"),
        Language(code: "vi",    name: "Vietnamese"),
        Language(code: "cy",    name: "Welsh"),
        Language(code: "af",    name: "Afrikaans"),
        Language(code: "sq",    name: "Albanian"),
        Language(code: "am",    name: "Amharic"),
        Language(code: "hy",    name: "Armenian"),
        Language(code: "az",    name: "Azerbaijani"),
        Language(code: "eu",    name: "Basque"),
        Language(code: "be",    name: "Belarusian"),
        Language(code: "bs",    name: "Bosnian"),
        Language(code: "my",    name: "Burmese"),
        Language(code: "ceb",   name: "Cebuano"),
        Language(code: "ny",    name: "Chichewa"),
        Language(code: "co",    name: "Corsican"),
        Language(code: "eo",    name: "Esperanto"),
        Language(code: "fr-CA", name: "French (Canadian)"),
        Language(code: "gl",    name: "Galician"),
        Language(code: "ka",    name: "Georgian"),
        Language(code: "ha",    name: "Hausa"),
        Language(code: "haw",   name: "Hawaiian"),
        Language(code: "hmn",   name: "Hmong"),
        Language(code: "ig",    name: "Igbo"),
        Language(code: "jw",    name: "Javanese"),
        Language(code: "la",    name: "Latin"),
        Language(code: "mi",    name: "Maori"),
        Language(code: "mn",    name: "Mongolian"),
        Language(code: "ne",    name: "Nepali"),
        Language(code: "ps",    name: "Pashto"),
        Language(code: "pt-BR", name: "Portuguese (Brazil)"),
        Language(code: "sm",    name: "Samoan"),
        Language(code: "gd",    name: "Scots Gaelic"),
        Language(code: "st",    name: "Sesotho"),
        Language(code: "sn",    name: "Shona"),
        Language(code: "sd",    name: "Sindhi"),
        Language(code: "so",    name: "Somali"),
        Language(code: "su",    name: "Sundanese"),
        Language(code: "tl",    name: "Tagalog"),
        Language(code: "tg",    name: "Tajik"),
        Language(code: "uz",    name: "Uzbek"),
        Language(code: "xh",    name: "Xhosa"),
        Language(code: "yi",    name: "Yiddish"),
        Language(code: "yo",    name: "Yoruba"),
        Language(code: "zu",    name: "Zulu")
    ]

    static func find(code: String) -> Language? {
        if code == autoDetect.code { return autoDetect }
        return all.first { $0.code == code }
    }
}
